
package br.com.caelum.estoque.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://caelum.com.br/estoquews/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @param tokenUsuario
     * @param parameters
     * @return
     *     returns br.com.caelum.estoque.soap.GetQuantidadesResponse
     */
    @WebMethod
    @WebResult(name = "getQuantidadesResponse", targetNamespace = "http://caelum.com.br/estoquews/v1", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetQuantidadesResponse getQuantidades(
        @WebParam(name = "getQuantidades", targetNamespace = "http://caelum.com.br/estoquews/v1", partName = "parameters")
        GetQuantidades parameters,
        @WebParam(name = "tokenUsuario", targetNamespace = "http://caelum.com.br/estoquews/v1", header = true, partName = "tokenUsuario")
        String tokenUsuario);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.caelum.estoque.soap.ItemEstoque
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuantidade", targetNamespace = "http://caelum.com.br/estoquews/v1", className = "br.com.caelum.estoque.soap.GetQuantidade")
    @ResponseWrapper(localName = "getQuantidadeResponse", targetNamespace = "http://caelum.com.br/estoquews/v1", className = "br.com.caelum.estoque.soap.GetQuantidadeResponse")
    public ItemEstoque getQuantidade(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
